---
version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - docker/publish:
          name: "Publish node-ci image"
          path: "./packages/node-ci"
          context: "gh-npm-public"
          docker-username: GH_PACKAGES_USER
          docker-password: GH_PACKAGES_PASS
          registry: docker.pkg.github.com
          image: "docker.pkg.github.com/kennship/docker-node/ci:latest"

orbs:
  docker: circleci/docker@0.5.18
