---
version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - docker/publish:
          name: "Publish node-ci image"
          path: "./packages/node-ci"
          context: "gh-npm-public"
          docker-username: DOCKER_HUB_USERNAME
          docker-password: DOCKER_HUB_PASSWORD
          image: "kennship/node-ci"

orbs:
  docker: circleci/docker@0.5.18
