---
version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - docker/publish:
          name: "Publish node-ci image"
          path: "./packages/node-ci"
          context: "gh-npm-public"
          docker-username: GH_PACKAGES_USERNAME
          docker-password: GH_PACKAGES_PASSWORD
          registry: docker.pkg.github.com
          image: "kennship/docker-node/ci"

orbs:
  docker: circleci/docker@0.5.18
